//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaning
    {
        public int ID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> CleaningDate { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual CleaningStatus CleaningStatus { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Room Room { get; set; }
    }
}
